name: run main.py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # Every day at 12:00

jobs:
  build_run:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code and copy it on runner
        uses: actions/checkout@v3 

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.9' 
          
      - name: Install package dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run the main script
        env:
          PORT: ${{ secrets.PORT }}
          SERVER: ${{ secrets.SERVER }}
          SENDER: ${{ secrets.SENDER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py