name: run main.py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *' # Every day at 17:00 (UTC)

jobs:
  build_run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10" 
          
      - name: Install package dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run the main script
        env:
          PORT: ${{ secrets.PORT }}
          SERVER: ${{ secrets.SERVER }}
          SENDER: ${{ secrets.SENDER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py